# Properties of HTS tapes

In [11]:
import mixtures_v2 as rm
import numpy as np
from IPython.display import display
import sympy as sy

mm = 1e-3
mum = 1e-6
MPa = 1e6
GPa = MPa*1e3

# thicknesses are TOTAL (accounting for multiple layers)
theva = {'Cu': {'E': 90*GPa, 'nu': 0.3, 'thick': 22*mum, 'G' : 90*GPa/(2*(1+0.3))},
        'ReBCO': {'E': 155*GPa, 'nu': 0.3, 'thick': 0*mum, 'G': 155*GPa/(2*(1+0.3))},
        'SS': {'E': 208*GPa, 'nu': 0.3, 'thick': 45*mum, 'G': 208*GPa/(2*(1+0.3))}
        }

In [12]:
thicknesses = np.array([])
moduli = np.array([])
Gi = np.array([])
nui = np.array([])

for mat, prop in theva.items():
    thicknesses = np.append(thicknesses, prop['thick'])
    moduli = np.append(moduli, prop['E'])
    Gi = np.append(Gi, prop['G'])
    nui = np.append(nui, prop['nu'])

names = []
for key, vals in theva.items():
    names.append(key)
print(names)    
print('thicknesses: \n', thicknesses/mum, '\n Moduli: \n', moduli/GPa, '\n Shear moduli: \n', Gi/GPa, '\n Poisson\'s ratii: \n' , nui)

tape_t = np.sum(thicknesses)

['Cu', 'ReBCO', 'SS']
thicknesses: 
 [22.  0. 45.] 
 Moduli: 
 [ 90. 155. 208.] 
 Shear moduli: 
 [34.61538462 59.61538462 80.        ] 
 Poisson's ratii: 
 [0.3 0.3 0.3]


In [13]:
# Mechanical calculations. Module: rm
err, ephiphi, ezz = sy.symbols('E_rr E_\phi\phi E_zz')
grphi, gphiz, grz = sy.symbols('G_r\phi G_\phi_z G_rz')
nuphir, nuphiz, nuzr = sy.symbols('v_\phi_r v_\phi_z v_zr')
Cbar, Sbar = sy.symbols('C S')

Er = rm.Ez(thicknesses, moduli)
Eth = rm.Ex(thicknesses, moduli)
Ez = Eth

Gthz = rm.Gxy(thicknesses, Gi)
Gthr = rm.Gxz(thicknesses, Gi)
Gzr = Gthr

nuthr = rm.nuxz(thicknesses, nui)
nuthz = rm.nuxy(thicknesses, nui, moduli)

Cc, Sc = rm.C_S_rthz(Er, Eth, nuthr, nuthz, Gthr, Gthz)

Crr = Cc[0,0]
Crth = Cc[0,1]
Crz = Cc[0,2]
Cthth = Cc[1,1]
Cthz = Cc[1,2]
Czz = Cc[2,2]

kk1 = np.sqrt(Cthth/Crr)

cc = sy.Matrix(Cc)
ss = sy.Matrix(Sc)

display(err, 
        Er,
        ephiphi,
        Eth,
        ezz,
        Ez,
        grphi,
        Gthr,
        gphiz,
        Gthz,
        grz,
        Gzr,
        nuphir,
        nuthr,
        nuphiz,
        nuthz,
        nuzr,
        nuthr,
        Cbar,
        cc,
       Sbar,
       ss)

E_rr

145402272200.32462

E_\phi\phi

169253731343.28357

E_zz

169253731343.28357

G_r\phi

55923950846.278694

G_\phi_z

65097588978.18599

G_rz

55923950846.278694

v_\phi_r

0.3

v_\phi_z

0.3

v_zr

0.3

C

Matrix([
[186629934516.196, 79984257649.7983, 79984257649.7983,                0,               0,                0],
[79984257649.7983, 220272078930.445, 90076900974.0729,                0,               0,                0],
[79984257649.7983, 90076900974.0729, 220272078930.445,                0,               0,                0],
[               0,                0,                0, 55923950846.2787,               0,                0],
[               0,                0,                0,                0, 65097588978.186,                0],
[               0,                0,                0,                0,               0, 55923950846.2787]])

S

Matrix([
[ 6.87747161627759e-12, -1.77248677248677e-12, -1.77248677248677e-12,                    0,                    0,                    0],
[-1.77248677248677e-12,  5.90828924162258e-12, -1.77248677248677e-12,                    0,                    0,                    0],
[-1.77248677248677e-12, -1.77248677248677e-12,  5.90828924162258e-12,                    0,                    0,                    0],
[                    0,                     0,                     0, 1.78814262023217e-11,                    0,                    0],
[                    0,                     0,                     0,                    0, 1.53615520282187e-11,                    0],
[                    0,                     0,                     0,                    0,                    0, 1.78814262023217e-11]])